@startuml
autonumber

activate Server
Client -> Server : Registriert sich beim Server
activate Client
Client -> Server : Fragt nach dem Startbild
Client <- Server : Sendet Startbild
actor Persons
Client <- Person : Setzt StartKoordinaten per Mausklick
Client -> Server : Sendet StartKoordinaten
Client -> Server : Holt Bild vom Server
... Beliebig oft ...
Person -> Client : beendet das Program
Client -> Server : Sende Cliente beendet
deactivate Client
note left: Server wird zurückgesetzt\n und wartet wieder auf Client

@enduml
